/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface TmiMiniCard {
        /**
          * Creator Details
         */
        "creatorid": number;
        /**
          * Creator Details
         */
        "creatorname": string;
        /**
          * Id of the Mini
         */
        "miniid": number;
        /**
          * Name of the Mini
         */
        "name": string;
        /**
          * Source site
         */
        "sourcesite": string;
        /**
          * Approval status of the Mini
         */
        "status": number;
        /**
          * Thumbnail URL
         */
        "thumbnail": string;
    }
    interface TmiNavBar {
        /**
          * Current selected page
         */
        "currentpage": string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLTmiMiniCardElement extends Components.TmiMiniCard, HTMLStencilElement {
    }
    var HTMLTmiMiniCardElement: {
        prototype: HTMLTmiMiniCardElement;
        new (): HTMLTmiMiniCardElement;
    };
    interface HTMLTmiNavBarElement extends Components.TmiNavBar, HTMLStencilElement {
    }
    var HTMLTmiNavBarElement: {
        prototype: HTMLTmiNavBarElement;
        new (): HTMLTmiNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "tmi-mini-card": HTMLTmiMiniCardElement;
        "tmi-nav-bar": HTMLTmiNavBarElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface TmiMiniCard {
        /**
          * Creator Details
         */
        "creatorid"?: number;
        /**
          * Creator Details
         */
        "creatorname"?: string;
        /**
          * Id of the Mini
         */
        "miniid"?: number;
        /**
          * Name of the Mini
         */
        "name"?: string;
        /**
          * Source site
         */
        "sourcesite"?: string;
        /**
          * Approval status of the Mini
         */
        "status"?: number;
        /**
          * Thumbnail URL
         */
        "thumbnail"?: string;
    }
    interface TmiNavBar {
        /**
          * Current selected page
         */
        "currentpage"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "tmi-mini-card": TmiMiniCard;
        "tmi-nav-bar": TmiNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "tmi-mini-card": LocalJSX.TmiMiniCard & JSXBase.HTMLAttributes<HTMLTmiMiniCardElement>;
            "tmi-nav-bar": LocalJSX.TmiNavBar & JSXBase.HTMLAttributes<HTMLTmiNavBarElement>;
        }
    }
}
