/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TmiAdminCard {
        "cost": string;
        "miniid": string;
        "status": string;
        "submitter": string;
        "thumbnail": string;
    }
    interface TmiAdminMiniRow {
        "miniid": string;
        "name": string;
        "source": string;
        "tagdata": string;
        "thumbnail": string;
        "type": string;
    }
    interface TmiDoSomethingButton {
        "data": string;
        "method": string;
        "text": string;
        "tmistyle": string;
        "url": string;
    }
    interface TmiMiniCard {
        /**
          * Creator Details
         */
        "creatorid": number;
        /**
          * Creator Details
         */
        "creatorname": string;
        /**
          * Id of the Mini
         */
        "miniid": number;
        /**
          * Name of the Mini
         */
        "name": string;
        /**
          * Source site
         */
        "sourcesite": string;
        /**
          * Approval status of the Mini
         */
        "status": number;
        /**
          * Thumbnail URL
         */
        "thumbnail": string;
    }
    interface TmiNavBar {
        /**
          * Current selected page
         */
        "currentpage": string;
    }
}
declare global {
    interface HTMLTmiAdminCardElement extends Components.TmiAdminCard, HTMLStencilElement {
    }
    var HTMLTmiAdminCardElement: {
        prototype: HTMLTmiAdminCardElement;
        new (): HTMLTmiAdminCardElement;
    };
    interface HTMLTmiAdminMiniRowElement extends Components.TmiAdminMiniRow, HTMLStencilElement {
    }
    var HTMLTmiAdminMiniRowElement: {
        prototype: HTMLTmiAdminMiniRowElement;
        new (): HTMLTmiAdminMiniRowElement;
    };
    interface HTMLTmiDoSomethingButtonElement extends Components.TmiDoSomethingButton, HTMLStencilElement {
    }
    var HTMLTmiDoSomethingButtonElement: {
        prototype: HTMLTmiDoSomethingButtonElement;
        new (): HTMLTmiDoSomethingButtonElement;
    };
    interface HTMLTmiMiniCardElement extends Components.TmiMiniCard, HTMLStencilElement {
    }
    var HTMLTmiMiniCardElement: {
        prototype: HTMLTmiMiniCardElement;
        new (): HTMLTmiMiniCardElement;
    };
    interface HTMLTmiNavBarElement extends Components.TmiNavBar, HTMLStencilElement {
    }
    var HTMLTmiNavBarElement: {
        prototype: HTMLTmiNavBarElement;
        new (): HTMLTmiNavBarElement;
    };
    interface HTMLElementTagNameMap {
        "tmi-admin-card": HTMLTmiAdminCardElement;
        "tmi-admin-mini-row": HTMLTmiAdminMiniRowElement;
        "tmi-do-something-button": HTMLTmiDoSomethingButtonElement;
        "tmi-mini-card": HTMLTmiMiniCardElement;
        "tmi-nav-bar": HTMLTmiNavBarElement;
    }
}
declare namespace LocalJSX {
    interface TmiAdminCard {
        "cost"?: string;
        "miniid"?: string;
        "status"?: string;
        "submitter"?: string;
        "thumbnail"?: string;
    }
    interface TmiAdminMiniRow {
        "miniid"?: string;
        "name"?: string;
        "source"?: string;
        "tagdata"?: string;
        "thumbnail"?: string;
        "type"?: string;
    }
    interface TmiDoSomethingButton {
        "data"?: string;
        "method"?: string;
        "onFetchCompleted"?: (event: CustomEvent<boolean>) => void;
        "text"?: string;
        "tmistyle"?: string;
        "url"?: string;
    }
    interface TmiMiniCard {
        /**
          * Creator Details
         */
        "creatorid"?: number;
        /**
          * Creator Details
         */
        "creatorname"?: string;
        /**
          * Id of the Mini
         */
        "miniid"?: number;
        /**
          * Name of the Mini
         */
        "name"?: string;
        /**
          * Source site
         */
        "sourcesite"?: string;
        /**
          * Approval status of the Mini
         */
        "status"?: number;
        /**
          * Thumbnail URL
         */
        "thumbnail"?: string;
    }
    interface TmiNavBar {
        /**
          * Current selected page
         */
        "currentpage"?: string;
    }
    interface IntrinsicElements {
        "tmi-admin-card": TmiAdminCard;
        "tmi-admin-mini-row": TmiAdminMiniRow;
        "tmi-do-something-button": TmiDoSomethingButton;
        "tmi-mini-card": TmiMiniCard;
        "tmi-nav-bar": TmiNavBar;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "tmi-admin-card": LocalJSX.TmiAdminCard & JSXBase.HTMLAttributes<HTMLTmiAdminCardElement>;
            "tmi-admin-mini-row": LocalJSX.TmiAdminMiniRow & JSXBase.HTMLAttributes<HTMLTmiAdminMiniRowElement>;
            "tmi-do-something-button": LocalJSX.TmiDoSomethingButton & JSXBase.HTMLAttributes<HTMLTmiDoSomethingButtonElement>;
            "tmi-mini-card": LocalJSX.TmiMiniCard & JSXBase.HTMLAttributes<HTMLTmiMiniCardElement>;
            "tmi-nav-bar": LocalJSX.TmiNavBar & JSXBase.HTMLAttributes<HTMLTmiNavBarElement>;
        }
    }
}
